---
title: "卒業研究（論文）マニュアル"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 0. 本マニュアルの狙いと想定する読者

 本マニュアルは、**卒業研究（guraduation research）または卒業論文（graduation thesis）を初めて書く（これから書こう）と考えている人[^1]に向けたマニュアル[^2]**です。その目的は、卒業に必要となる研究や論文の進め方・書き方について、多少の「道しるべ」を指し示すことにあります。
 
 まずはじめに断っておくべきことが1つあります。それは、本マニュアルを読んだからといって、誰しもが卒業研究や卒業論文を書けるようになるわけではないということです。このことをレシピ本と料理の関係を例にとって、少し説明したいと思います。料理が上手くなりたいと思った人なら、一度は料理本に目を通した、あるいは実際に手に取り利用した人がいると思います。当たり前ですが、料理本にはレシピが書かれています。料理に必要となる材料、その適量、調理の進め方など、作りたい料理を作るために必要な情報が書いてあります。

 ですが、レシピ本を読んだからといって、必ず「美味しい料理」ができるわけはありません。つまり、必要なものややり方を知っていても、上手くやれるわけではないということです。感のいい人なら、もうわかりましたね。このマニュアルもそうしたレシピ本と同じです。このマニュアルを読んだからといって、「良い」あるいは「面白い」論文や研究ができるわけではありません。ですが、必要なものもやり方も知らなければ、「料理（つまり研究や論文を書くこと）」はそもそもできません。ですから、本マニュアルを読むことで、自分がやることを理解し、心の準備ができれば良いなと思っています。
 
### * マニュアル作成の経緯

 本マニュアルを作ろうとしたきっかけは、卒業研究や卒業論文（以下、卒研と省略）をやろうとする学生が、毎年同じ悩みや質問を聞いてくる経験にあります。お決まりの質問は、**「なんで卒研をしないといけないの！？」**、**「研究・論文て何？」**、**「卒研って何を（どう）すればいいの」**、**「卒研のテーマはどうすれば見つかるの？」**というものでしょうか。自分の学生時代を振り返っても、たしかに少なくとも1回は、同じ疑問を持っていました。ですから、まずは本マニュアルではそうした質問を考えた上で、卒研の具体的な進め方などを説明していくことにしたいと思います。

### * 構成

 では、具体的にこのマニュアルで話す内容を簡単に説明します。まず第1章では、卒研に関して、先生と学生の想いの違いや研究と論文とは何かを考えていきます。毎年毎年、学生さんからすごく敵対的に「なんで卒研なんてあるの？？？」と質問され、どう回答すればいいか悩むことがあります。ですが、このことは学生さんからすれば、僕から納得のいく答えをもらえていないということです。それでは、誰も納得しないのは当たり前です。ですから、最初に卒論に対する先生の考え[^3]を述べ、研究と論文とは何かを説明していきたいと思います。
 
  次に第2章では、卒研の「中身」を説明します。ここでいう中身とは、卒研を行う上で絶対に必要になるものだと思ってください。つまり、前に出したレシピ本の例に沿って言えば、料理に必要となるもの（具材, 調理道具など）です。さらに、そうした卒研に必要となるものに関して、どうすれば卒研のひな形を作れるかを考えます。世の中には色々な研究[^4]がありますが、ここではそれらに共通するものを説明したいと思います。
  
  第2章が「中身」であるのに対して、第3章は「形式」について考えるパートです。つまり、卒研に必要になるものを、どのように見せれば（組み立てれば）良いのかということを説明します。具体的には、ここでは卒研に関して、序論、本論、考察、結論とはどういうものかを考えます。ここで改めて注意してほしい点は、本章で述べることは「型」であって、絶対的なものではりません。ですから、基本となる形を理解したら、その中の細かい順番や内容は自分自身の研究に合わせていってください。
  
  第4章は、引用（ひょう窃）について説明します。これは、学生さんがよく聞いてくる*「なんでWiki（ウィキ）はダメなの？」*という頻出問題を想定した内容です。この質問に答えるためには、引用についてきちんと説明する必要があります。言い換えれば、引用（の重要性や意義）がわかったら、「なんでWiki（ウィキ）はダメなの？」という質問はしなくなると思います。またその際、学生さんがよく誤解する*「引用したらダメ（＝卒研は全部オリジナルじゃないといけない）」*という考えにも答えたいと思います。
  
  第5章と第6章は、卒研に関する補助的[^5]内容です。そこでは、卒研とくに論文を書く上で重要になる言葉遣いを説明します。また、第6章では本マニュアルで使用した参考文献に加え、学生のみなさんが自分自身の力で卒研を進める上で参考になる書籍等を載せました。（内心では、ぜひ一度は目を通してもらいたいと思っている部分ではあります）


## 1. 卒業研究（論文）とは

### * 先生と学生で異なる"想い"

 ここでは、学生さんからよく聞かれる「なんで卒研をしないといけないの！？」という疑問を考えていきます。確かに、卒研を経験した人の多くは、一度は「なんで卒研って必要なの？」と思ったことがあるのではなないでしょうか。この質問を受けると、毎回思うことが1つあります。それは、卒研に関して、学生と教員の間で"想い"がズレているということです。誤解のないように一言付け加えるなら、それは学生あるいは教員のどっちが悪いという話ではないです。ここで言いたいことはあくまで、学生と教員で卒研に対する“想い”のズレを感じるということです。そのズレに関して、学生と教員（先生）それぞれの想いを整理してみましょう。
 
 まずは学生の想いを考えてみます。
 
 
 

### * 研究・論文とは何か


## 2. 研究（論文）の「中身」

### * 「問い」の条件


### * 「問い」の見つけ方


### * 研究（論文）の基本形


## 3. 研究（論文）の「形式」

### * 基本の形


### * 序論


### * 本論


### * 考察


### * 結論


## 4. 引用（ひょう窃）について


### * なぜ引用（参考文献）が必要なのか？


### * 引用と参考文献の関係


### * 引用の書き方


### * 参考文献の書き方


## 5. おまけ：論文における言葉遣い


## 6. 参考文献


[^1]:当然ですが、2回以上研究や論文をやってみた経験がある人達も歓迎です。自分自身としては、そうした人たちにも何かしら気づきがあるマニュアルになっていればよいかなと思います。

[^2]:正確には、本マニュアルは「マニュアル」ではありません。その理由は、マニュアルとは本来プログラム化が可能なものであるからです。つまり、何をすればどうなるかが事前にはっきりしているからこそ、マニュアルは作れるのです。ですが卒業研究は、後でも述べますが、問いから進め方まで、一人ひとり全く違います。そのため、「本当の意味のマニュアル」は作れないのです。

[^3]:筆者の個人的見解です。

[^4]:ここでは社会科学系の研究を念頭に入れています。

[^5]:文章構成や日本語の問題は、もちろん「補助的」な内容ではありません。ですが、便宜上、本マニュアルでは補助的内容としました。